deploy:
  runs-on: ubuntu-latest
  needs: build_and_push
  env:
    DB_USER: ${{ secrets.DB_USER }}
    DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    DB_NAME: ${{ secrets.DB_NAME }}
    SUDO_PASSWORD: ${{ secrets.PASSWORD }} # Добавлено новое окружение для пароля sudo
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Render configs
      run: |
        mkdir deploy
        cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
        cat docker_ci_config.py | envsubst > deploy/docker_config.py
    - name: Copy files to server
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        source: "deploy/docker-compose.yaml,deploy/docker_config.py"
        target: "anya_app_ci"
        strip_components: 1
    - name: Deploy app
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        env:
          SUDO_PASSWORD: ${{ secrets.PASSWORD }}
        script: |
          cd anya_app_ci
          echo "${SUDO_PASSWORD}" | sudo -S docker-compose up -d
